### ISSUE TITLE
error

### ISSUE THREAD

**Issue by kokpk** [SwimmingTiger/MessageClassifier#2]
60x ...rfaceMessageClassifier\MessageClassifier-v0.3.2.lua:23: attempt to concatenate local 'playerGUID' (a nil value)
...rfaceMessageClassifier\MessageClassifier-v0.3.2.lua:23: in function `filterFunc'
FrameXML\ChatFrame.lua:2990: in function `ChatFrame_MessageEventHandler'
VanasKoS\modules\Synchronizer.lua:938: in function <VanasKoS\modules\Synchronizer.lua:930>
(tail call): ?
FrameXML\ChatFrame.lua:2713: in function <FrameXML\ChatFrame.lua:2706>
WebDKP\WhisperDKP.lua:1: in function <WebDKP\WhisperDKP.lua:1>
(tail call): ?
(tail call): ?
[string "*:OnEvent"]:1: in function <[string "*:OnEvent"]:1>

Locals:
frame = ChatFrame1 {
 SetJustifyV = <function> defined =[C]:-1
 RefreshIfNecessary = <function> defined =[C]:-1
 OnPostShow = <function> defined =[C]:-1
 CalculateLineAlphaValueFromTimestamp = <function> defined =[C]:-1
 isLayoutDirty = false
 tellTimer = 492157.128000
 isDisplayDirty = true
 GetFading = <function> defined =[C]:-1
 IsTextCopyable = <function> defined =[C]:-1
 shouldFadeAfterInactivity = false
 SetIndentedWordWrap = <function> defined =[C]:-1
 GetJustifyV = <function> defined =[C]:-1
 SetFont = <function> defined =[C]:-1
 GetMaxLines = <function> defined =[C]:-1
 GetIndentedWordWrap = <function> defined =[C]:-1
 buttonSide = "left"
 GetFont = <function> defined =[C]:-1
 checkedGMOTD = true
 SetMaxLines = <function> defined =[C]:-1
 CalculateSelectingCharacterIndicesForVisibleLine = <function> defined =[C]:-1
 PageUp = <function> defined =[C]:-1
 RefreshDisplay = <function> defined =[C]:-1
 SetFontObject = <function> defined =[C]:-1
 textIsCopyable = false
 SetOnScrollChangedCallback = <function> defined =[C]:-1
 CalculateNumVisibleLines = <function> defined =[C]:-1
 overrideFadeTimestamp = 492269.592000
 MarkDisplayDirty = <function> defined =[C]:-1
 GetMessageInfo = <function> defined =[C]:-1
 GetOnScrollChangedCallback = <function> defined =[C]:-1
 AtTop = <function> defined =[C]:-1
 GetFontObject = <function> defined =[C]:-1
 fontStringPool = <table> {
 }
 CanEffectivelyFade = <function> defined =[C]:-1
 OnPreSizeChanged = <function> defined =[C]:-1
 OnPostMouseUp = <function> defined =[C]:-1
 GetSpacing = <function> defined =[C]:-1
 OnPreLoad = <function> defined =[C]:-1
 SetSpacing = <function> defined =[C]:-1
 name = "综合"
 CalculateLineSpacing = <function> defined =[C]:-1
 AddMessage = <function> defined @ShestakUI\Modules\Chat\ChatFrames.lua:14
 InitializeFontableFrame = <function> defined =[C]:-1
 GetShadowColor = <function> defined =[C]:-1
 isUninteractable = false
 SetOnTextCopiedCallback = <function> defined =[C]:-1
 mouseOutTime = 0
 AcquireFontString = <function> defined =[C]:-1
 TransformMessages = <function> defined =[C]:-1
 SetShadowColor = <function> defined =[C]:-1
 buttonFrame = ChatFrame1ButtonFrame {
 }
 HasFontObject = <function> defined =[C]:-1
 isDocked = 1
 GetOnTextCopiedCallback = <function> defined =[C]:-1
 SetFading = <function> defined =[C]:-1
 OnPostHide = <function> defined =[C]:-1
 alternativeDefaultLanguage = "兽人语"
 isInitialized = 1
 ScrollByAmount = <function> defined =[C]:-1
 GetInsertMode = <function> defined =[C]:-1
 SetTimeVisible = <function> defined =[C]:-1
 hasOwnFontObject = true
 Clear = <function> defined =[C]:-1
 oldAlpha = 0
 channelList = <table> {
 }
 GetTimeVisible = <function> defined =[C]:-1
 MarkLayoutDirty = <function> defined =[C]:-1
 SetTextCopyable = <function> defined =[C]:-1
 BackFillMessage = <function> defined =[C]:-1
 UnpackageEntry = <function> defined =[C]:-1
 FontStringContainer = <unnamed> {
 }
 SetShadowOffset = <function> defined =[C]:-1
 messageTypeList = <table> {
 }
 flashTimer = 0.494000
 timeVisibleSecs = 120
 PackageEntry = <function> defined =[C]:-1
 MakeFontObjectCustom = <function> defined =[C]:-1
 fontObject = table: 00000248176FF8D0 {
 }
 SetInsertMode = <function> defined =[C]:-1
 mouseInTime = 0
 ScrollDown = <function> defined =[C]:-1
 zoneChannelList = <table> {
 }
 SetScrollOffset = <function> defined =[C]:-1
 onDisplayRefreshedCallback = <function> defined =[C]:-1
 insertMode = 2
 ResetSelectingText = <function> defined =[C]:-1
 GetTextColor = <function> defined =[C]:-1
 defaultLanguage = "兽人语"
 ResetAllFadeTimes = <function> defined =[C]:-1
 skinned = true
 GatherSelectedText = <function> defined =[C]:-1
 GetNumVisibleLines = <function> defined =[C]:-1
 ScrollUp = <function> defined =[C]:-1
 0 = <userdata>
 IsSelectingText = <function> defined =[C]:-1
 fadeDurationSecs = 3
 ScrollToBottom = <function> defined =[C]:-1
 ScrollToTop = <function> defined =[C]:-1
 OnFontObjectUpdated = <function> defined =[C]:-1
 CallOnDisplayRefreshed = <function> defined =[C]:-1
 AdjustMessageColors = <fun

**Comment by SwimmingTiger** [comment]
This may be a fix:
https://github.com/SwimmingTiger/MessageClassifier/commit/f8f37b5e715dc3652ecd67e8a56ab98a03d29dcb

Please tell me if v0.3.3 fixes this problem.

已尝试在v0.3.3中修复，不知道有没有效果。
