### ISSUE TITLE
Option to keep regular chat

### ISSUE THREAD

**Issue by Jinnai** [SwimmingTiger/MessageClassifier#4]
It would be nice to have the Message Browser available but also still be able to see regular chat in the normal chat frame.

**Comment by SwimmingTiger** [comment]
You should always be able to see regular chat in the normal chat frame. If you can't see them, a Lua script error should have occurred. You can consider using BugGrabber + BugSack to capture.

**Comment by SwimmingTiger** [comment]
In addition, if you want to bypass the duplicate message filter, you can set `Min seconds for duplicate messages appear` to 1 (enter 1 directly in the input box below and press Enter). So you can see all duplicate messages.

**Comment by YihaoPeng** [comment]
Or, have you checked "Hide from chat window" for any rule. If yes, please uncheck. If you check "Hide from chat window" for the rule that matches any content, it will also cause what you said.

**Comment by Jinnai** [comment]
Yes it works again now. It must have been a conflict with another addon. This issue can be closed.
